### ISSUE TITLE
No hooked integration?

### ISSUE THREAD

**Issue by Vaamerr** [cloudnode-pro/BankAccounts#8]
[20:54:17 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[20:54:18 ERROR]: [com.zaxxer.hikari.pool.HikariPool] HikariPool-1 - Exception during pool initialization.
java.sql.SQLNonTransientConnectionException: Socket fail to connect to host:address=(host=localhost)(port=3306)(type=primary). Connection refused: no further information
        at org.mariadb.jdbc.client.impl.ConnectionHelper.connectSocket(ConnectionHelper.java:137) ~[BankAccounts-1.0.1.jar:?]
        at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:99) ~[BankAccounts-1.0.1.jar:?]
        at org.mariadb.jdbc.Driver.connect(Driver.java:70) ~[BankAccounts-1.0.1.jar:?]
        at org.mariadb.jdbc.Driver.connect(Driver.java:101) ~[BankAccounts-1.0.1.jar:?]
        at org.mariadb.jdbc.Driver.connect(Driver.java:27) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[BankAccounts-1.0.1.jar:?]
        at pro.cloudnode.smp.bankaccounts.BankAccounts.setupDbSource(BankAccounts.java:90) ~[BankAccounts-1.0.1.jar:?]
        at pro.cloudnode.smp.bankaccounts.BankAccounts.onEnable(BankAccounts.java:36) ~[BankAccounts-1.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:580) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:491) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
        at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
        at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.net.Socket.connect(Socket.java:633) ~[?:?]
        at org.mariadb.jdbc.client.impl.ConnectionHelper.connectSocket(ConnectionHelper.java:131) ~[BankAccounts-1.0.1.jar:?]
        ... 25 more
[20:54:18 ERROR]: Error occurred while enabling BankAccounts v1.0.1 (Is it up to date?)
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Socket fail to connect to host:address=(host=localhost)(port=3306)(type=primary). Connection refused: no further information
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[BankAccounts-1.0.1.jar:?]
        at pro.cloudnode.smp.bankaccounts.BankAccounts.setupDbSource(BankAccounts.java:90) ~[BankAccounts-1.0.1.jar:?]
        at pro.cloudnode.smp.bankaccounts.BankAccounts.onEnable(BankAccounts.java:36) ~[BankAccounts-1.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:580) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:491) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.sql.SQLNonTransientConnectionException: Socket fail to connect to host:address=(host=localhost)(port=3306)(type=primary). Connection refused: no further information
        at org.mariadb.jdbc.client.impl.ConnectionHelper.connectSocket(ConnectionHelper.java:137) ~[BankAccounts-1.0.1.jar:?]
        at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:99) ~[BankAccounts-1.0.1.jar:?]
        at org.mariadb.jdbc.Driver.connect(Driver.java:70) ~[BankAccounts-1.0.1.jar:?]
        at org.mariadb.jdbc.Driver.connect(Driver.java:101) ~[BankAccounts-1.0.1.jar:?]
        at org.mariadb.jdbc.Driver.connect(Driver.java:27) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[BankAccounts-1.0.1.jar:?]
        ... 16 more
Caused by: java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
        at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
        at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.net.Socket.connect(Socket.java:633) ~[?:?]
        at org.mariadb.jdbc.client.impl.ConnectionHelper.connectSocket(ConnectionHelper.java:131) ~[BankAccounts-1.0.1.jar:?]
        at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:99) ~[BankAccounts-1.0.1.jar:?]
        at org.mariadb.jdbc.Driver.connect(Driver.java:70) ~[BankAccounts-1.0.1.jar:?]
        at org.mariadb.jdbc.Driver.connect(Driver.java:101) ~[BankAccounts-1.0.1.jar:?]
        at org.mariadb.jdbc.Driver.connect(Driver.java:27) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[BankAccounts-1.0.1.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[BankAccounts-1.0.1.jar:?]
        ... 16 more
[20:54:18 INFO]: [BankAccounts] Disabling BankAccounts v1.0.1
[20:54:18 ERROR]: Error occurred (in the plugin loader) while disabling BankAccounts v1.0.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.zaxxer.hikari.HikariDataSource.close()" because "this.dbSource" is null
        at pro.cloudnode.smp.bankaccounts.BankAccounts.onDisable(BankAccounts.java:55) ~[BankAccounts-1.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:580) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:491) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Vaamerr** [comment]
is it possible to disable JDBC url?

**Comment by zefir-git** [comment]
Hi! Currently, only MariaDB with JDBC is implemented. Sorry, forgot to mention that in the description.

I can work on adding support for H2 (data is stored in a file locally) if that works for you.

**Comment by Vaamerr** [comment]
yes it will be very good not all of us use MariaDB )))

**Comment by zefir-git** [comment]
> yes it will be very good not all of us use MariaDB )))

That's understandable. I'm mainly developing this plugin for a server on which MariaDB is used. H2 support shouldn't be difficult to implement and would probably be way more useful for most people.

**Comment by Vaamerr** [comment]
you do good things hope you don't abandon this development

**Comment by Vaamerr** [comment]
the only plugin with bank accounts

**Comment by zefir-git** [comment]
@Vaamerr SQLite support has been implemented in 1.1.0 ([open on Modrinth](https://modrinth.com/plugin/bankaccounts/version/1.1.0)). See more here: #10
